# Generated by Django 3.0.8 on 2021-03-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HimnosHimnarioCristiano',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('himno', models.TextField()),
                ('nota', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota')),
                ('tipo', models.CharField(choices=[('Adoración', 'Adoración'), ('Alabanza', 'Alabanza'), ('Especiales', 'Especiales'), ('Cumpleaños', 'Cumpleaños'), ('Himno de Fe y Alabanza', 'Himno de Fe y Alabanza'), ('Cantico al Señor', 'Cantico al Señor')], default='Adoración', max_length=50)),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Número de Himno')),
                ('url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Himnario Cristiano',
                'verbose_name_plural': 'Himnario Cristiano',
            },
        ),
    ]
