# Generated by Django 3.0.8 on 2021-03-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HimnarioCristiano', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='himnoshimnariocristiano',
            name='number',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Número de Himno'),
        ),
    ]
