# Generated by Django 3.0.8 on 2021-03-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HimnarioCristiano', '0002_auto_20210313_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='himnoshimnariocristiano',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Adoración', 'Adoración'), ('Alabanza', 'Alabanza'), ('Especiales', 'Especiales'), ('Cumpleaños', 'Cumpleaños'), ('Himno de Fe y Alabanza', 'Himno de Fe y Alabanza'), ('Cantico al Señor', 'Cantico al Señor')], default='Adoración', max_length=50, null=True),
        ),
    ]
