# Generated by Django 3.0.8 on 2021-03-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alabanza',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('tono', models.CharField(choices=[('mayor', 'Mayor'), ('menor', 'Menor')], default='mayor', max_length=10)),
                ('nota', models.CharField(choices=[('C', 'C'), ('Cm', 'Cm'), ('D', 'D'), ('Dm', 'Dm'), ('E', 'E'), ('Em', 'Em'), ('F', 'F'), ('Fm', 'Fm'), ('G', 'G'), ('Gm', 'Gm'), ('A', 'A'), ('Am', 'Am'), ('B', 'B'), ('Bm', 'Bm')], default='C', max_length=10)),
                ('tipo', models.CharField(default='Adoracion', max_length=25)),
                ('autor', models.CharField(max_length=50, verbose_name='Autor')),
                ('himno', models.TextField()),
                ('url', models.CharField(max_length=150, verbose_name='Url')),
                ('estado', models.CharField(default='nuevo', max_length=50, verbose_name='Estado')),
                ('numerotono', models.IntegerField(default=0, max_length=5)),
            ],
            options={
                'verbose_name': 'Alabanza',
                'verbose_name_plural': 'Alabanzas',
            },
        ),
        migrations.AlterField(
            model_name='himno',
            name='himno',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='himno',
            name='numero',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
