# Generated by Django 3.0.8 on 2021-03-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_himnosfealabanza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alabanza',
            options={'verbose_name': 'Coro de Alabanza', 'verbose_name_plural': 'Coros de Alabanza'},
        ),
        migrations.AlterModelOptions(
            name='himno',
            options={'verbose_name': 'Himno de Adoración', 'verbose_name_plural': 'Himnos de Adoración'},
        ),
        migrations.AlterField(
            model_name='alabanza',
            name='autor',
            field=models.CharField(max_length=50, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='alabanza',
            name='estado',
            field=models.CharField(default='nuevo', max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='alabanza',
            name='url',
            field=models.CharField(max_length=150, null=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='himno',
            name='autor',
            field=models.CharField(max_length=50, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='himno',
            name='estado',
            field=models.CharField(default='nuevo', max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='himno',
            name='url',
            field=models.CharField(max_length=150, null=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='himnosfealabanza',
            name='autor',
            field=models.CharField(max_length=50, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='himnosfealabanza',
            name='estado',
            field=models.CharField(default='nuevo', max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='himnosfealabanza',
            name='url',
            field=models.CharField(max_length=150, null=True, verbose_name='Url'),
        ),
    ]
