# Generated by Django 3.0.8 on 2021-03-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210307_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='HimnosHimnarioCristiano',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('himno', models.TextField()),
                ('nota', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota')),
                ('tipo', models.CharField(choices=[('Adoración', 'Adoración'), ('Alabanza', 'Alabanza'), ('Especiales', 'Especiales'), ('Cumpleaños', 'Cumpleaños'), ('Himno de Fe y Alabanza', 'Himno de Fe y Alabanza'), ('Cantico al Señor', 'Cantico al Señor')], default='Adoración', max_length=50)),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Número de Himno')),
                ('url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Himnario Cristiano',
                'verbose_name_plural': 'Himnario Cristiano',
            },
        ),
        migrations.AlterField(
            model_name='alabanza',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='alabanza',
            name='estado',
            field=models.CharField(blank=True, default='nuevo', max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='alabanza',
            name='tipo',
            field=models.CharField(choices=[('Alabanza', 'Alabanza'), ('Misioneros', 'Misioneros'), ('Evangelisticos', 'Evangelisticos')], default='Alabanza', max_length=25),
        ),
        migrations.AlterField(
            model_name='alabanza',
            name='url',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='himno',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='himno',
            name='estado',
            field=models.CharField(blank=True, default='nuevo', max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='himno',
            name='url',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='himnosfealabanza',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='himnosfealabanza',
            name='estado',
            field=models.CharField(blank=True, default='nuevo', max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='himnosfealabanza',
            name='url',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Url'),
        ),
    ]
