# Generated by Django 3.0.8 on 2021-03-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210313_0929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HimnosHimnarioCristiano',
        ),
    ]
