# Generated by Django 5.1.5 on 2025-01-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_delete_himnoshimnariocristiano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alabanza',
            name='estado',
            field=models.CharField(blank=True, choices=[('nuevo', 'nuevo'), ('', '')], default='nuevo', max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='himno',
            name='estado',
            field=models.CharField(blank=True, choices=[('nuevo', 'nuevo'), ('', '')], default='nuevo', max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='himno',
            name='tipo',
            field=models.CharField(choices=[('Adoracion', 'Adoracion'), ('Misioneros', 'Misioneros'), ('Evangelisticos', 'Evangelisticos')], default='Adoracion', max_length=25),
        ),
        migrations.AlterField(
            model_name='himnosfealabanza',
            name='estado',
            field=models.CharField(blank=True, choices=[('nuevo', 'nuevo'), ('', '')], default='nuevo', max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='himnosfealabanza',
            name='tipo',
            field=models.CharField(choices=[('Congregacional', 'Congregacional'), ('Misioneros', 'Misioneros'), ('Evangelisticos', 'Evangelisticos')], default='Congregacional', max_length=25),
        ),
    ]
