# Generated by Django 5.1.5 on 2025-02-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_alabanza_estado_alter_himno_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='himnosycoros',
            fields=[
                ('id_himno', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('tono', models.CharField(choices=[('mayor', 'Mayor'), ('menor', 'Menor')], default='mayor', max_length=10)),
                ('nota', models.CharField(choices=[('C', 'C'), ('Cm', 'Cm'), ('D', 'D'), ('Dm', 'Dm'), ('E', 'E'), ('Em', 'Em'), ('F', 'F'), ('Fm', 'Fm'), ('G', 'G'), ('Gm', 'Gm'), ('A', 'A'), ('Am', 'Am'), ('B', 'B'), ('Bm', 'Bm')], default='C', max_length=10)),
                ('tipo', models.CharField(choices=[('Alabanza', 'Alabanza'), ('Misioneros', 'Misioneros'), ('Evangelisticos', 'Evangelisticos')], default='Alabanza', max_length=25)),
                ('autor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Autor')),
                ('himno', models.TextField()),
                ('url', models.CharField(blank=True, max_length=150, null=True, verbose_name='Url')),
                ('estado', models.CharField(blank=True, choices=[('nuevo', 'nuevo'), ('', '')], default='nuevo', max_length=50, null=True, verbose_name='Estado')),
                ('numerotono', models.IntegerField(default=0, max_length=5)),
                ('categoria', models.CharField(choices=[('Alabanza', 'Alabanza'), ('Misioneros', 'Misioneros'), ('Evangelisticos', 'Evangelisticos')], default='Adoracion', max_length=25)),
            ],
            options={
                'verbose_name': 'Himno y Coro',
                'verbose_name_plural': 'Himnos y Coros',
            },
        ),
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.CharField(max_length=50, verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='tipos',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
    ]
