# Generated by Django 5.1.5 on 2025-02-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_himnosycoros_notas_tipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alabanza',
            name='numerotono',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='himno',
            name='numerotono',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='himnosfealabanza',
            name='numerotono',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='himnosycoros',
            name='numerotono',
            field=models.IntegerField(default=0),
        ),
    ]
