# Generated by Django 5.1.5 on 2025-02-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_delete_alabanza_delete_himno_delete_himnosfealabanza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='himnosycoros',
            name='autor',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='himnosycoros',
            name='url',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Url'),
        ),
    ]
